update smalot/pdfparser dependency
atgp/factur-x pull request #7
Opened 2021-04-16 16:13 UTC by dsampaolo

All tests are OK

2021-04-20 07:15 UTC, aegypius requested changes

2021-04-20 07:15 UTC, aegypius commented on composer.json
> +    "name": "bleetic/factur-x",
@dsampaolo I think this change should not be in this pull-request.

2021-04-21 17:51 UTC, caugner requested changes

2021-04-21 17:51 UTC, caugner commented on composer.json
> +    "name": "bleetic/factur-x",
```suggestion
    "name": "atgp/factur-x",
```

2021-06-01 08:54 UTC, lucas-gp commented
Pull request merged, thanks you.

2021-06-01 08:54 UTC, closed without merging